---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/25 16:10
--- Content: 模糊Shader
---

-- 示例用法如下
--[[
node:addLuaComponent(Blur,
{
    blur = 0.03,        -- 模糊度
    brightness = 1,     -- 亮度
    defines = {         -- 宏定义
        sampleNum = 5,  -- 采样次数
        blurType = Blur.BLUR_TYPE.FROSTED   -- 模糊类型
    }
})
--]]

local BaseShader = require("src.components.shaders.BaseShader")
local Blur = class("Blur", BaseShader)

Blur.VERT = "res/shaders/noMV.vert"
Blur.FRAG = "res/shaders/blur.frag"

Blur.BLUR_TYPE = {
    FROSTED = 1,    -- 磨砂效果
    FUZZY = 2,      -- 有点视力下降的感觉
    RADIAL = 3,     -- 径向模糊
}

local DEFINE_SAMPLE_NUM = 5

local BLUR_NAME = "u_blur"
local BRIGHTNESS_NAME = "u_brightness"
local CENTER_NAME = "u_center"
local DEFAULT_BLUR = 0.03
local DEFAULT_BRIGHTNESS = 1

function Blur:ctor(node, data)
    Blur.super.ctor(self, node, data)
end

function Blur:initData(data)
    data = data or {}
    Blur.super.initData(self, data)

    -- 模糊度
    self.blur = data.blur or DEFAULT_BLUR
    -- 亮度
    self.brightness = data.brightness or DEFAULT_BRIGHTNESS
    -- 径向模糊的中心
    self.center = data.center or cc.p(0.5, 0.5)
    -- 宏定义选项 - 模糊类型
    self.defines.blurType = self.defines.blurType or Blur.BLUR_TYPE.FROSTED
    -- 宏定义选项 - 采样次数，当blurType等于FUZZY/RADIAL有效
    self.defines.sampleNum = self.defines.sampleNum or DEFINE_SAMPLE_NUM
end

function Blur:setDefaultUniform()
    self:setBlur(self.blur, false)
    self:setBrightness(self.brightness, false)
    if self.defines.blurType == Blur.BLUR_TYPE.RADIAL then
        self:setCenter(self.center)
    end
end

function Blur:setBlur(blur, immediately)
    self.blur = blur
    self:setFloat(BLUR_NAME, blur, immediately)
end

function Blur:setBrightness(brightness, immediately)
    self.brightness = brightness
    self:setFloat(BRIGHTNESS_NAME, brightness, immediately)
end

function Blur:setCenter(center, immediately)
    self.center = cc.pNormalize(self.center)
    self:setVec2(CENTER_NAME, center, immediately)
end

return Blur