---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/13 11:05
--- Content: 亮度
---
local BaseShader = require("src.components.shaders.BaseShader")
local Brightness = class("Brightness", BaseShader)

Brightness.VERT = "res/shaders/mvp.vsh"
Brightness.FRAG = "res/shaders/brightness.fsh"

local DEFAULT_BRIGHTNESS = 0.5

local BRIGHTNESS_NAME = "u_brightness"

function Brightness:ctor(node, data)
    Brightness.super.ctor(self, node, data)
end

function Brightness:initData(data)
    data = data or {}
    Brightness.super.initData(self, data)

    -- 亮度
    self.brightness = data.brightness or DEFAULT_BRIGHTNESS
end

function Brightness:initDefaultUniform()
    Brightness.super.initDefaultUniform(self)

    self:setBrightness(self.brightness)
end

function Brightness:setBrightness(brightness)
    self.brightness = brightness
    self:setFloat(BRIGHTNESS_NAME, brightness)
end

return Brightness