---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/24 15:21
---
local BaseShader = require("src.components.shaders.BaseShader")
local Outline = class("Outline", BaseShader)

Outline.VERT = "res/shaders/noMV.vert"
Outline.FRAG = "res/shaders/outline.frag"

local COLOR_NAME = "u_color"
local WIDTH_NAME = "u_width"
local DEFAULT_COLOR = cc.c3b(255, 0, 0)
local DEFAULT_WIDTH = 0.02

function Outline:ctor(node, data)
    Outline.super.ctor(self, node, data)
end

function Outline:initData(data)
    data = data or {}
    Outline.super.initData(self, data)

    -- 描边颜色
    self.color = data.color or DEFAULT_COLOR
    -- 描边宽度
    self.width = data.width or DEFAULT_WIDTH
    self.defines.threshold = self.defines.threshold or 0.1
end

function Outline:setDefaultUniform()
    self:setColor(self.color, false)
    self:setWidth(self.width, false)
end

function Outline:setColor(color, immediately)
    self.color = color
    self:setColor3f(COLOR_NAME, color, immediately)
end

function Outline:setWidth(width, immediately)
    self.width = width
    self:setFloat(WIDTH_NAME, width, immediately)
end

return Outline