---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/3 9:58
---
local ShaderTest = class("ShaderTest", BaseNode)

function ShaderTest:ctor()
    self:testOutline()
    self:testBlur()
end

function ShaderTest:testOutline()
    local avatar = cc.Sprite:create("res/bg_avatar_default.png")
                     :move(100, 150)
                     :addTo(self)
    avatar:addLuaComponent(Outline)
end

function ShaderTest:testBlur()
    local avatar2 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(100, 400)
                      :addTo(self)
    avatar2:addLuaComponent(Blur, {
        blurType = Blur.BLUR_TYPE.NORMAL,
        radius = 5
    })

    local avatar3 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(300, 400)
                      :addTo(self)
    avatar3:addLuaComponent(Blur, {
        blurType = Blur.BLUR_TYPE.FROSTED,
        sampleNum = 5
    })

    local avatar4 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(500, 400)
                      :addTo(self)
    avatar4:addLuaComponent(Blur, {
        sampleNum = 5,
        blurType = Blur.BLUR_TYPE.RADIAL,
        radius = 10,
        center = cc.p(0.5, 0.8)
    })

    local avatar5 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(700, 400)
                      :addTo(self)
    avatar5:addLuaComponent(Blur, {
        sampleNum = 5,
        blurType = Blur.BLUR_TYPE.GAUSSIAN,
        radius = 7
    })
end

return ShaderTest