---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/3 9:58
---
local Blur = require("src.components.shaders.Blur")
local Outline = require("src.components.shaders.Outline")
local Brightness = require("src.components.shaders.Brightness")
local Ripple = require("src.components.shaders.Ripple")
local Clickable = require("src.components.touch.Clickable")
local Touchable = require("src.components.touch.Touchable")
local Draggable = require("src.components.touch.Draggable")
local ShaderTest = class("ShaderTest", BaseNode)

function ShaderTest:ctor()
    --self:testOutline()
    --self:testBlur()
    self:testBrightness()
    self:testRipple()
end

function ShaderTest:testOutline()
    local avatar = cc.Sprite:create("res/bg_avatar_default.png")
                     :move(100, 150)
                     :addTo(self)
    avatar:addLuaComponent(Outline)
end

function ShaderTest:testBlur()
    local avatar2 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(100, 400)
                      :addTo(self)
    avatar2:addLuaComponent(Blur, {
        blurType = Blur.BLUR_TYPE.NORMAL,
        radius = 5
    })

    local avatar3 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(300, 400)
                      :addTo(self)
    avatar3:addLuaComponent(Blur, {
        blurType = Blur.BLUR_TYPE.FROSTED,
        sampleNum = 5
    })

    local avatar4 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(500, 400)
                      :addTo(self)
    avatar4:addLuaComponent(Blur, {
        sampleNum = 5,
        blurType = Blur.BLUR_TYPE.RADIAL,
        radius = 10,
        center = cc.p(0.5, 0.8)
    })

    local avatar5 = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(700, 400)
                      :addTo(self)
    avatar5:addLuaComponent(Blur, {
        sampleNum = 5,
        blurType = Blur.BLUR_TYPE.GAUSSIAN,
        radius = 7
    })
end

function ShaderTest:testBrightness()
    local pos = cc.p(100, 700)
    local avatar = cc.Sprite:create("res/bg_avatar_default.png")
                      :move(pos)
                      :addTo(self)
    avatar:addLuaComponent(Brightness, {
        brightness = 0.8,
    })

    local rect = avatar:getBoundingBox()
    local maxDistance =  500
    avatar:addTouchListener({
        onBegan = function()
            return true
        end,
        onMoved = function(touch)
            local distance = DistanceUtils.pToRect(touch:getLocation(), rect)
            local brightness = 0.5
            if distance < maxDistance then
                brightness = (maxDistance - distance) / maxDistance
            end
            brightness = cc.clampf(brightness, 0.5, 1.0)
            avatar:getLuaComponent(Brightness):setBrightness(brightness)
        end
    })

    avatar:addTouchListener({
        onEnded = function(touch)
            print("on ended")
        end
    })
end

function ShaderTest:testRipple()
    local pos = cc.p(300, 700)
    local avatar = cc.Sprite:create("res/bg_avatar_default.png")
                     :move(pos)
                     :addTo(self)
    avatar:addLuaComponent(Ripple, {
        center = cc.p(0.5, 0.4)
    })

    avatar:addLuaComponent(Clickable, {
        onClick = function(event)
            local p = event.sender.node:convertToNodeSpace(event.position)
            avatar:getLuaComponent(Ripple):start(p)
        end
    })
    avatar:addLuaComponent(Draggable, {
        reboundEnabled = true
    })
end

return ShaderTest