---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/15 17:09
---
local TocaConstants = {}

-- 长按时多久后有触摸反馈
TocaConstants.PRESS_DURATION = 0.3

-- 松手放置时，弹跳信息
TocaConstants.BOUNCE_DURATION = 0.2
TocaConstants.BOUNCE_HEIGHT = 20
TocaConstants.BOUNCE_NUM = 1

return TocaConstants