---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/6/1 17:53
---
eventManager = cc.load("event").new():bind({})

BaseNode = require "app.framework.base.BaseNode"