---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/6/1 17:54
---
local RubberBand = class("RubberBand", BaseNode)

function RubberBand:ctor(data)
    RubberBand.super.ctor(self, data)
end

return RubberBand