---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/27 14:52
---
local Log = {}

local ERROR_FILE = "error.txt"

function Log.error(msg, toConsole)
    toConsole = toConsole == nil and true or toConsole
    local messages = {
        '',
        '----------------------------------------',
        'LOG DATE: ' .. os.date("%c"),
        'LUA ERROR: ' .. tostring(msg),
        debug.traceback(),
        '----------------------------------------',
        '',
    }
    msg = table.concat(messages, "\n")
    if toConsole then
        print(msg)
    end

    io.writeFile(cc.FileUtils:getInstance():getWritablePath() .. ERROR_FILE, msg, "a+")
end

function Log.info(msg)
    if DEBUG then
        local info = debug.getinfo(2)
        local messages = {
            info.short_src,
            ":",
            "[",
            info.name,
            ":",
            info.currentline,
            "]",
            ":",
            msg
        }
        msg = table.concat(messages, "")
    end
    print(msg)
end

return Log