---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/25 18:31
---
local UIHelper = {}

function UIHelper.center(size)
    return cc.p(size.width / 2, size.height / 2)
end

return UIHelper