---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/25 18:31
---
local UIUtils = {}

function UIUtils.center(size)
    return cc.p(size.width / 2, size.height / 2)
end

local __debugNodeIncrementalRGB = 1
function UIUtils.debug(target, isCascade)
    __debugNodeIncrementalRGB = (__debugNodeIncrementalRGB * 43897) % 0xffffff
    local size = target:getContentSize()
    if isCascade then
        local rect = target:convertRectToNodeSpace(target:getCascadeBoundingBoxToWorld())
        size = cc.size(rect.width, rect.height)
    end
    local layout = target:getChildByName("__DEBUG_NODE__") or ccui.Layout:create():addTo(target)
    layout:setBackGroundColorType(ccui.LayoutBackGroundColorType.solid)
    layout:setBackGroundColor(hexColor(__debugNodeIncrementalRGB))
    layout:setBackGroundColorOpacity(165)
    layout:setContentSize(size)
    layout:setName("__DEBUG_NODE__")
end

return UIUtils