---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/25 18:31
---
local UIUtils = {}

function UIUtils.center(size)
    return cc.p(size.width / 2, size.height / 2)
end

function UIUtils.getTextureResType(path)
    if cc.SpriteFrameCache:getInstance():getSpriteFrame(path) then
        return ccui.TextureResType.plistType
    end
    return ccui.TextureResType.localType
end

function UIUtils.updateImageTexture(node, path, status)
    if not string.isValid(path) then return end

    local resType = UIUtils.getTextureResType(path)
    if iskindof(node, "cc.Sprite") then
        if resType == ccui.TextureResType.localType then
            node:setTexture(path)
        else
            node:setSpriteFrame(path)
        end
    elseif iskindof(node, "ccui.ImageView") or iskindof(node, "ccui.Sprite9Scale") then
        node:loadTexture(path, resType)
    elseif iskindof(node, "ccui.Button") then
        if status == "normal" then
            node:loadTextureNormal(path, resType)
        else
            node:loadTexturePressed(path, resType)
        end
    end
end

local __debugNodeIncrementalRGB = 1
function UIUtils.debug(target, isCascade)
    __debugNodeIncrementalRGB = (__debugNodeIncrementalRGB * 43897) % 0xffffff
    local size = target:getContentSize()
    if isCascade then
        local rect = target:convertRectToNodeSpace(target:getCascadeBoundingBoxToWorld())
        size = cc.size(rect.width, rect.height)
    end
    local layout = target:getChildByName("__DEBUG_NODE__") or ccui.Layout:create():addTo(target)
    layout:setBackGroundColorType(ccui.LayoutBackGroundColorType.solid)
    layout:setBackGroundColor(hexColor(__debugNodeIncrementalRGB))
    layout:setBackGroundColorOpacity(165)
    layout:setContentSize(size)
    layout:setName("__DEBUG_NODE__")
end

return UIUtils