---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/6/1 17:57
---
local GeometryConstants = {}

GeometryConstants.PI = 2 * math.asin(1.0)

GeometryConstants.EPS = 0.05
GeometryConstants.EPS_X = 0.005
GeometryConstants.EPS_L = 0.0005
GeometryConstants.EPS_M = 0.00005
GeometryConstants.EPS_S = 0.000005

GeometryConstants.SHAPE = {
    UNKNOWN     = 0,
    POINT       = 1,
    SEGMENT     = 2,
    LINE        = 3,
    TRIANGLE    = 10,
    QUADRANGLE          = 20,
    RECTANGLE           = 21,
    ROUNDED_RECTANGLE   = 22,
    ELLIPTIC_RECTANGLE  = 23,
    CIRCLE          = 30,
    HALF_CIRCLE     = 31,
    ELLIPSE         = 40,
    HALF_ELLIPSE    = 41
}

return GeometryConstants