---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/6/2 15:21
---
local Node = cc.Node

local touchListener

function Node:delayAction(callback, delay)
    return self:runAction(cc.Sequence:create(
            cc.DelayTime:create(delay or 0),
            cc.CallFunc:create(function()
                doCallback(callback)
            end)))
end

function Node:repeatAction(callback, duration)
    return self:runAction(cc.RepeatForever:create(cc.Sequence:create(
            cc.CallFunc:create(callback),
            cc.DelayTime:create(duration)
    )))
end

function Node:addTouchEvent(onBegan, onMoved, onEnded, onCanceled)
    self:removeTouchEvent()

    touchListener = cc.EventListenerTouchOneByOne:create()
    if onBegan then
        touchListener:registerScriptHandler(onBegan, cc.Handler.EVENT_TOUCH_BEGAN)
    end
    if onMoved then
        touchListener:registerScriptHandler(onMoved, cc.Handler.EVENT_TOUCH_MOVED)
    end
    if onEnded then
        touchListener:registerScriptHandler(onEnded, cc.Handler.EVENT_TOUCH_ENDED)
    end
    if onCanceled then
        touchListener:registerScriptHandler(onCanceled, cc.Handler.EVENT_TOUCH_CANCELLED)
    end
    self:getEventDispatcher():addEventListenerWithSceneGraphPriority(touchListener, self)
    return touchListener
end

function Node:removeTouchEvent()
    self:getEventDispatcher():removeEventListener(touchListener)
end