---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/28 16:01
---
local TouchConstants = {}

TouchConstants.ON_BEGAN = "on-began"
TouchConstants.ON_MOVED = "on-moved"
TouchConstants.ON_ENDED = "on-ended"
TouchConstants.ON_CANCELED = "on-canceled"
TouchConstants.ON_LONG_TOUCH = "on-long-touch"
TouchConstants.ON_CLICK = "on-click"
TouchConstants.ON_DESTROY = "on-destroy"

TouchConstants.STYLES = {
    NONE    = 'none',
    COLOR   = 'color',
    SCALE   = 'scale',
    IMAGE   = 'image'
}

TouchConstants.TYPES = {
    CLICK = 'click',
    LONG_TOUCH = 'long-touch'
}

TouchConstants.STATUS = {
    NORMAL = 'normal',
    PRESSED = 'pressed'
}

TouchConstants.ANCHOR_TYPES = {
    CENTER          = "center",
    LEFT_TOP        = "left_top",
    LEFT_BOTTOM     = "left_bottom",
    LEFT_CENTER     = "left_center",
    RIGHT_TOP       = "right_top",
    RIGHT_BOTTOM    = "right_bottom",
    RIGHT_CENTER    = "right_center",
    TOP_CENTER      = "top_center",
    CENTER_BOTTOM   = "center_bottom",
    CUSTOM          = "custom",
}

return TouchConstants