---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/28 16:01
---
local TouchConstants = {}

TouchConstants.ON_BEGAN = "on-began"
TouchConstants.ON_MOVED = "on-moved"
TouchConstants.ON_ENDED = "on-ended"
TouchConstants.ON_CANCELED = "on-canceled"
TouchConstants.ON_LONG_TOUCH = "on-long-touch"
TouchConstants.ON_CLICK = "on-click"
TouchConstants.ON_DESTROY = "on-destroy"

TouchConstants.STYLES = {
    NONE    = 'none',
    COLOR   = 'color',
    SCALE   = 'scale',
    IMAGE   = 'image'
}

TouchConstants.TYPES = {
    CLICK = 'click',
    LONG_TOUCH = 'long-touch'
}

TouchConstants.STATUS = {
    NORMAL = 'normal',
    PRESSED = 'pressed'
}

TouchConstants.DRAG_ALIGN_TYPES = {
    CENTER          = "center",
    LEFT_TOP        = "left_top",
    LEFT_BOTTOM     = "left_bottom",
    LEFT_CENTER     = "left_center",
    RIGHT_TOP       = "right_top",
    RIGHT_BOTTOM    = "right_bottom",
    RIGHT_CENTER    = "right_center",
    CENTER_TOP      = "center_top",
    CENTER_BOTTOM   = "center_bottom",
    CUSTOM          = "custom",
}

TouchConstants.DRAG_ALIGN_ANCHOR = {
    [TouchConstants.DRAG_ALIGN_TYPES.CENTER]         = cc.p(0.5, 0.5),
    [TouchConstants.DRAG_ALIGN_TYPES.LEFT_TOP]       = cc.p(0, 1),
    [TouchConstants.DRAG_ALIGN_TYPES.LEFT_BOTTOM]    = cc.p(0, 0),
    [TouchConstants.DRAG_ALIGN_TYPES.LEFT_CENTER]    = cc.p(0, 0.5),
    [TouchConstants.DRAG_ALIGN_TYPES.RIGHT_TOP]      = cc.p(1, 1),
    [TouchConstants.DRAG_ALIGN_TYPES.RIGHT_BOTTOM]   = cc.p(1, 0),
    [TouchConstants.DRAG_ALIGN_TYPES.RIGHT_CENTER]   = cc.p(1, 0.5),
    [TouchConstants.DRAG_ALIGN_TYPES.CENTER_TOP]     = cc.p(0.5, 1),
    [TouchConstants.DRAG_ALIGN_TYPES.CENTER_BOTTOM]  = cc.p(0.5, 0),
}

return TouchConstants