---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/12/13 18:20
--- Content: 触摸组件
---
local Touchable = class("Touchable", BaseComponent)

Touchable.ON_BEGAN = "on-began"
Touchable.ON_MOVED = "on-moved"
Touchable.ON_ENDED = "on-ended"
Touchable.ON_CANCELED = "on-canceled"
Touchable.ON_LONG_TOUCH = "on-long-touch"
Touchable.ON_DESTROY = "on-destroy"

function Touchable:ctor(node, data)
    cc.load("event").new():bind(self)
    Touchable.super.ctor(self, node, data)
    self:initData(data)
    self:initListener()
end

function Touchable:initData(data)
    data = data or {}
    -- 响应的区域
    self.shape = data.shape or {}
    -- 是否启用长按
    self.isLongTouchEnabled = data.isLongTouchEnabled or false
    -- 触发长按的时间阈值
    self.longTouchThreshold = data.longTouchThreshold or 0.5
    -- touch的各个阶段
    self.onBeganFunc, self.onMovedFunc = data.onBegan, data.onMoved
    self.onEndedFunc, self.onCanceledFunc = data.onEnded, data.onCanceled
    self.onLongTouchFunc = data.onLongTouch

    self.touchListenerId = -1
    self.longTouchTimer = nil
    self.touchBeganPosition = cc.p(0, 0)
    self.touchCurrPosition = cc.p(0, 0)
end

function Touchable:initListener()
    self.touchListenerId = self.node:addTouchEvent({
        onBegan = handler(self, self.onTouchBegan),
        onMoved = handler(self, self.onTouchMoved),
        onEnded = handler(self, self.onTouchEnded),
        onCanceled = handler(self, self.onTouchCanceled),
    })
end

function Touchable:onTouchBegan(touch)
    local position = touch:getLocation()
    local isHit = self:isHit(position)
    self.touchBeganPosition, self.touchCurrPosition = position, position
    if isHit then
        self:dispatchEvent({name = Touchable.ON_BEGAN, sender = self, position = position})
        doCallback(self.onBeganFunc, {sender = self, position = position})
        self:startLongTouchTimer()
    end
    return isHit
end

function Touchable:onTouchMoved(touch)
    local position = touch:getLocation()
    self.touchCurrPosition = position
    self:dispatchEvent({name = Touchable.ON_MOVED, sender = self, position = position})
    doCallback(self.onMovedFunc, {sender = self, position = position})
end

function Touchable:onTouchEnded(touch)
    self:stopLongTouchTimer()

    local position = touch:getLocation()
    local isHit = self:isHit(position)
    self.touchCurrPosition = position
    self:dispatchEvent({name = Touchable.ON_ENDED, sender = self, position = position, isHit = isHit})
    doCallback(self.onEndedFunc, {sender = self, position = position, isHit = isHit})
end

function Touchable:onTouchCanceled()
    self:stopLongTouchTimer()

    self:dispatchEvent({ name = Touchable.ON_CANCELED, sender = self})
    doCallback(self.onCanceledFunc, {sender = self})
end

function Touchable:startLongTouchTimer()
    if not self.isLongTouchEnabled then return end

    self.longTouchTimer = self.node:delayAction(function()
        self:onLongTouch()
    end, self.longTouchThreshold)
end

function Touchable:stopLongTouchTimer()
    if self.longTouchTimer and isObjectExist(self.longTouchTimer) then
        self.node:stopAction(self.longTouchTimer)
        self.longTouchTimer = nil
    end
end

function Touchable:onLongTouch()
    local position = self.touchCurrPosition
    local isHit = self:isHit(position)
    self:dispatchEvent({name = Touchable.ON_LONG_TOUCH, sender = self, isHit = isHit, position = position})
    doCallback(self.onLongTouchFunc, {sender = self, isHit = isHit, position = position})
end

function Touchable:isHit(location)
    if not self.node:isAncestorsVisible() then return false end

    local position = self.node:convertToNodeSpace(location)
    if next(self.shape) then
        return IntersectionUtils.pInPolygon(position, self.shape)
    elseif type(self.node.isHit) == "function" then
        return self.node:isHit(position)
    else
        position = self.node:getParent():convertToNodeSpace(location)
        return cc.rectContainsPoint(self.node:getBoundingBox(), position)
    end
end

function Touchable:setOnLongTouch(func)
    if func and type(func) == "function" then
        self.onLongTouchFunc = func
    end
end

function Touchable:setOnBegan(func)
    if func and type(func) == "function" then
        self.onBeganFunc = func
    end
end

function Touchable:setOnMoved(func)
    if func and type(func) == "function" then
        self.onMovedFunc = func
    end
end

function Touchable:setOnEnded(func)
    if func and type(func) == "function" then
        self.onEndedFunc = func
    end
end

function Touchable:setOnCanceled(func)
    if func and type(func) == "function" then
        self.onCanceledFunc = func
    end
end

function Touchable:onDestroy()
    self.node:removeTouchEvent(self.touchListenerId)
    self:stopLongTouchTimer()
    self:dispatchEvent({name = Touchable.ON_DESTROY})
end

return Touchable