---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/6/2 10:34
---

require "src.config"
require "src.cocos.init"

-- base
Singleton = require("src.base.Singleton")
BaseNode = require("src.base.BaseNode")
BaseScene = require("src.base.BaseScene")

-- managers
eventManager = require("src.managers.eventManager")

GeometryConstants = require 'src.utils.geometry.GeometryConstants'
IntersectionUtils = require 'src.utils.geometry.IntersectionUtils'

GraphicsNode = require 'src.widgets.GraphicsNode'
RubberBand = require 'src.widgets.RubberBand'

cc.disable_global()