---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/24 11:36
---
local BaseScene = class("BaseScene", function()
    return display.newScene()
end)

function BaseScene:ctor()
    self._globalListeners = {}
    self:enableNodeEvents()
end

function BaseScene:onEnter(...)
    print('---------Scene', self.__cname, 'onEnter')
end

function BaseScene:onExit()
    print('---------Scene', self.__cname, 'onExit')

    self:disableNodeEvents()
    self:removeAllGlobalListeners()
    display.removeUnusedSpriteFrames()
end

function BaseScene:addGlobalListener(eventName, callback)
    local handle = eventManager:addEventListener(eventName, callback)
    table.insert(self._globalListeners, handle)
    return handle
end

function BaseScene:removeAllGlobalListeners()
    table.walk(self._globalListeners, function(handle)
        eventManager:removeEventListener(handle)
    end)
    self._globalListeners = {}
end

return BaseScene