---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/24 11:30
---
local Singleton = class('Singleton')

function Singleton.getInstance(instance)
    if instance._instance == nil then
        instance._instance = instance.new()
    end
    return instance._instance
end

return Singleton