---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tomas.
--- DateTime: 2021/11/24 11:30
---
local Singleton = class('Singleton')

function Singleton.getInstance(cls)
    if not cls.__instance == nil then
        cls.__instance = cls.new()
    end
    return cls.__instance
end

return Singleton